### ISSUE TITLE
Trouble getting SteamVR Input to work with OpenVR XR Plugin

### ISSUE THREAD

**Issue by ll-M-ll** [ValveSoftware/unity-xr-plugin#9] opened 2020-07-15 19:39 UTC
Apparently SteamVR-XRPlugin beta doesn't work at all, Or maybe i dont know how to use it, Because when I finally got everything to work I've noticed that none of my input were  working, I have switched the input system twice trying to figure out why but in the end I've come to the conclusion either SteamVR input doesn't work as long as XR plugin is active or I just am not using it right.... the Old code that used to move the player using SteamVR is no longer detecting anything.

**things I've tried :**
1 -  removing and disabling components.
2-  I used `Debug.log` approach to see where the rabbit hole in my code.
3- steamVR live input, it wasn't detecting anything.
4- I switched between the new and the old Input system, Neither of them worked.

On the other hand when I used **XR INPUT DEBUGGER** with the n**ew input system**
everything I did was working was being detected correctly

**Comment by zite** [comment] 2020-07-17 20:47
The current versions of the OpenVR Unity XR Plugin do not support the unity input system. For input you'll need to use SteamVR Input via the SteamVR Unity Plugin. We hope this will be consolidated with OpenXR.

**Comment by ll-M-ll** [comment] 2020-07-17 20:57
> The current versions of the OpenVR Unity XR Plugin do not support the unity input system. For input you'll need to use SteamVR Input via the SteamVR Unity Plugin. We hope this will be consolidated with OpenXR.

I know that is what I used, Even with the script it didn't read any input, all my SteamVR input weren't working, I hope you guys either give us a full tutorial on how to do this on a video ( 2 mins ) or please fix it with an update, because this is crucial to the deveopment workflow.

**Comment by zite** [comment] 2020-07-22 21:27
Can you provide an editor.log when steamvr input is not working? What kind or errors are you seeing? You can find the editor.log in %localappdata%/Unity/Editor/Editor.log

**Comment by totalschaden** [comment] 2020-07-29 11:11
Cant get Input to work with Unitys New Input Manager, when the Plugin was still in Branch, Prev. 2, it was working just fine. Was it dropped ? Will it be available again in a later version ?
I moved back to Prev. 2 for now.

**Comment by zite** [comment] 2020-07-29 17:12
I'm going to assume the original issue was resolved by an update. @totalschaden please see this issue: https://github.com/ValveSoftware/unity-xr-plugin/issues/16

**Comment by ll-M-ll** [comment] 2020-07-29 18:06
@zite  there is no log, i have 2 players.. steam code is there on the player it just doesn't detect anything, I've tried the live input of steam to make sure that it's not anything with the code. there is no input there.

**Comment by zite** [comment] 2020-07-29 18:16
@ll-M-ll I'm not sure I understand. You have an external player (not yourself) that isn't getting input? You should be able to get logs from builds as well. https://docs.unity3d.com/Manual/LogFiles.html

**Comment by ll-M-ll** [comment] 2020-07-29 18:29
ok I dont why it's hard to understand but
its simply not working:

when I use steamVR 2.5 I can move the player using the controllers
once I install steamVR2.6beta2 it nothing happens , no errors , no input , nothing... players is in the spawned location doing nothing.

**Comment by zite** [comment] 2020-07-29 19:44
I'm trying to troubleshoot the issue with you so we can get your scenario working again. For that I need more information about your scenario. A log would be very helpful in determining why input is failing for you and not for other scenarios.

Have you enabled the OpenVR Loader in the XR Management settings window?

**Comment by ll-M-ll** [comment] 2020-07-29 22:06
@zite i keep getting this error every now and then 
`static Void PreferencesGUI() does not match UnityEditor.SettingsProviderAttribute expected signature.
 Use static UnityEditor.SettingsProvider signature()
UnityEditor.SettingsWindow:OnEnable()`
I static Void PreferencesGUI() does not match UnityEditor.SettingsProviderAttribute expected signature.
 Use static UnityEditor.SettingsProvider signature()
UnityEditor.SettingsWindow:OnEnable()`

and yes I have enabled OpenVRLoader  and steamVR launched normally... I will try again tomorrow with preview10 ... I guess I have to delete XR and steamVR folder then install steamVRbeta3 , right ?

**Comment by zite** [comment] 2020-07-29 22:30
I'm not sure what that error is unfortunately. Yeah, deleting and reinstalling is what I'd recommend. There will be a beta4 and preview 12 up by tomorrow that you should use. And if it doesn't work this time please send a log.

**Comment by zite** [comment] 2020-07-30 22:09
Preview 12 is up along with beta4 of the steamvr unity plugin. I'd recommend deleting the SteamVR folder and reinstalling with this: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b4

If it still doesn't work, make sure preview-12 of the OpenVR XR Plugin is installed, and try restarting unity a couple times. Sometimes unity seems to have issues releasing the DLLs.

**Comment by ll-M-ll** [comment] 2020-07-31 15:45
@zite ok I've deleted the SteamVR folder from the Assets folder then removed OpenVR DeskTop from the package Manger.
then I've installed 2.6.0b4 using the installer
I was greeted by this error on the console 
`static Void PreferencesGUI() does not match UnityEditor.SettingsProviderAttribute expected signature.
 Use static UnityEditor.SettingsProvider signature()
UnityEditor.SettingsWindow:OpenProjectSettings()`

then I've attempted to install XR plugin manager from the project Settings . there was a message that poped I think it was talking about builtIn XR and it wanted to replace it - I had 2 options yes and cancel ... I've tried the cancel .
open VR Loader was not there SO I've checked OpenVR Desktop from the package Manager it was installed 

Also worst mentioning that I couldn't find any of the preview tools.
also I had this on my log 
`[SteamVR Setup] Installing OpenVR package...
UnityEngine.Debug:Log(Object)
Valve.VR.SteamVR_AutoEnableVR:Update() (at Assets/SteamVR/Editor/SteamVR_AutoEnableVR.cs:219)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions(`

so I've deleted the SteamVR folder again and removed OpenVR Desktop and attempted to reinstall the package again.
![image](https://user-images.githubusercontent.com/43939767/89052145-909b5000-d355-11ea-9e47-43c57cbd6385.png)
that is the end of it I guess.. no openVR Loader

**Comment by ll-M-ll** [comment] 2020-07-31 16:27
SO I've notice that  2.6.0b4 is for 2020.1 and  2.6.0b3 is for 2019.3/4 .. since that is what I'm using I have went to that link {https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/installer} after installing  2.6.0b4  that got me the OpenVR loader.


`/Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.12/Runtime/x64/XRSDKOpenVR.dll' with error 'The specified procedure could not be found.
'.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`
maybe that was because SteamVR was not on .. so I turned it on and cleared the message , it didn't pop back on my console again.

I'll test the game and come bak

**Comment by zite** [comment] 2020-07-31 17:15
FYI, OpenVR Desktop is a unity made package that is for Unity 2019.4 and below. It uses the old VR interfaces that they depreciated. OpenVR XR Plugin is what you'll need for 2020.1 and above.
Thanks for doing all this troubleshooting. I think we're all trying to get to an SDK abstraction that's easy to use, but that can be a struggle at times.

**Comment by ll-M-ll** [comment] 2020-07-31 17:38
@zite I got those issues on Running >
(2 times) 
`Plugins: Failed to load ....../Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.12/Runtime/x64/XRSDKOpenVR.dll' with error 'The specified procedure could not be found.
'.
UnityEngine.XR.Management.XRGeneralSettings:AttemptInitializeXRSDKOnLoad()
`
( 1 )time only 
` Failed to load '....../Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.12/Runtime/x64/XRSDKOpenVR.dll' with error 'The specified procedure could not be found.
'.
Unity.XR.OpenVR.OpenVRLoader:Initialize() (at Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.12/Runtime/OpenVRLoader.cs:183)
UnityEngine.XR.Management.XRGeneralSettings:AttemptInitializeXRSDKOnLoad()
`
( 1 )time 
`DllNotFoundException: XRSDKOpenVR
Unity.XR.OpenVR.OpenVRLoader.Initialize () (at Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.12/Runtime/OpenVRLoader.cs:183)
UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRManagerSettings.cs:169)
UnityEngine.XR.Management.XRGeneralSettings.InitXRSDK () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:175)
UnityEngine.XR.Management.XRGeneralSettings.AttemptInitializeXRSDKOnLoad () (at Library/PackageCache/com.unity.xr.management@3.2.13/Runtime/XRGeneralSettings.cs:148)`
`

**Comment by ll-M-ll** [comment] 2020-07-31 17:44
this is worst than preview 2 so far... preview 2 can launch the game without steamVR input being detected , this cant even track the headset ....

**Comment by zite** [comment] 2020-08-01 01:03
That seems crazy. Can you verify that the package installed the dll correctly? Go to your project directory, then /Library/PackageCache/com.valvesoftware.unity.openvr@1.0.0-preview.12/Runtime/x64/ and let me know what the filesize of XRSDKOpenVR.dll

**Comment by ll-M-ll** [comment] 2020-08-01 12:40
![image](https://user-images.githubusercontent.com/43939767/89101862-46bd7300-d404-11ea-8aa8-b34aad8c3f48.png)

ok I have some compiler erros now but it's based on my code issue because I'm testing it on an older version 
I will test it again and I'll let u know when I'm done
but all I've done is upgrading this from 2.1.2 to 2.1.4 
![image](https://user-images.githubusercontent.com/43939767/89101934-e7ac2e00-d404-11ea-88ad-b0f30a72e17a.png)

or maybe because I relaunched the program.

**Comment by ll-M-ll** [comment] 2020-08-01 13:11
I got the [cameraRig] prefab to work finally ... but it was lagging so badly and I had 2 errors 
`Screen position out of view frustum (screen pos 0.000000, 0.000000, 1000.000000) (Camera rect 0 0 1440 1792)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

`Screen position out of view frustum (screen pos 1440.000000, 0.000000, 1000.000000) (Camera rect 0 0 1440 1792)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

the position of the rig was 0,0.8,0

**Comment by zite** [comment] 2020-08-02 21:57
Were there any warnings? Were those errors being repeated? Those errors are a known issue we're working through on start, but shouldn't cause lag.

**Comment by kajbeugels** [comment] 2020-08-27 19:45
@zite I am having trouble getting Input to work for OpenVR hardware, the documentation and information about this subject is very limited, so I might misunderstand, but if I understand it correctly the OpenXR package for Unity is only rendering, there currently is no way for detecting (button!) input using only the OpenXR package?

I am trying to avoid using SteamVRs input, and instead handle all Input through Unitys Input system, but it seems this isn't possible at the moment.

And if button Input for OpenVR devices is indeed not working through OpenXR, can you say when/if it's going to come?

**Comment by zite** [comment] 2020-08-28 05:10
Just to be clear, we're spending a lot of time internally on OpenXR so we
will have a spec compliant runtime. Other game engines are in the process
of supporting OpenXR. Unity has named their proprietary input abstraction
"Unity XR", which is not directly OpenXR compatible. All the XR VR AR
namings of things has unfortunately been confusing for everyone (including
the people making them).
To directly answer your question, the OpenVR Unity XR plugin only does
rendering, not input. Currently you must use the SteamVR Unity Plugin
(SteamVR Input) to get vr input in unity 2020.1+. If you're on 2019 or
earlier you can still use the old stuff.

**Comment by kajbeugels** [comment] 2020-08-28 06:50
Alright thanks for getting back, you are totally right about the current state of development for VR being confusing, I hope OpenXR will unify all of the platforms for us developers.

I will stick to SteamVR for now then, thanks for the quick response!

**Comment by ROBYER1** [comment] 2020-09-23 22:34
> The current versions of the OpenVR Unity XR Plugin do not support the unity input system. For input you'll need to use SteamVR Input via the SteamVR Unity Plugin. We hope this will be consolidated with OpenXR.

Is there any roadmap or timeline for this?

**Comment by Immersive-Matthew** [comment] 2020-09-23 22:41
I have read all the comments and cannot believe this issue is even a thing.  How on earth was this even missed?  Is this a Unity issue or Valve or both and like @ROBYER1 said, what is the timeline to get this addressed as I too need this fixed.  As a Unity VR developer it is hard enough to make everything work without missing and critical parts in the stack.

**Comment by stevenjj** [comment] 2020-09-24 21:18
> To directly answer your question, the OpenVR Unity XR plugin only does
> rendering, not input. Currently you must use the SteamVR Unity Plugin
> (SteamVR Input) to get vr input in unity 2020.1+. If you're on 2019 or
> earlier you can still use the old stuff.

Thank you for clarifying this. The example interaction scene in SteamVR/InteractionSystem/Samples/Interactions_Example.unity works perfectly fine. Som I was wondering why the HTC Pro Vive headset and controller tracking works but not the inputs when this plugin is tested with the example XR interactions package https://github.com/Unity-Technologies/XR-Interaction-Toolkit-Examples (Tested with Unity 2020.1.3f1).

The simple workaround is to continue using the SteamVR input scripts, which shouldn't be an issue for those who have been developing with SteamVR but want to render via the latest Unity XR plugin.

Echoing @ROBYER1 's question is there a timeline or plan for integrating both the Unity and SteamVR input managers as a single API?

Thanks for your time.

**Comment by ceitel** [comment] 2020-09-28 16:39
For anyone wondering, here is a list of the Device usages available through the UnityXR-Input system for the following loaders (running a WMR HMD)

OpenVR Loader:
DevicePosition, DeviceRotation, DeviceVelocity, DeviceAngularVelocity, TrackingState, IsTracked

WMR Loader:
TrackingState, IsTracked, DevicePosition, DeviceRotation, DeviceVelocity, DeviceAngularVelocity, BatteryLevel, Primary2DAxis, Primary2DAxisTouch, Primary2DAxisClick, Secondary2DAxis, Secondary2DAxisClick, Trigger, TriggerButton, Grip, GripButton, MenuButton, PointerPosition, PointerRotation, SourceLossRisk, SourceMitigationDirection

Seems strange to me that they were able to expose the select few common device usages that they did but chose(?) not to expose the others?

Is also frustrating that the Unity docs seem to tell another story of what usages are available:
https://docs.unity3d.com/2020.1/Documentation/Manual/xr_input.html

Echoing @ROBYER1  's question Is there any roadmap or timeline for this?

Thanks for your time

**Comment by ROBYER1** [comment] 2020-09-28 16:41
@ceitel Thanks for sharing, others will find that useful. I found those out the hard way unfortunately!

Again asking for a timeline or roadmap, even if it's vague.

**Comment by pollumi** [comment] 2020-10-19 19:15
Hello @zite 

Could you please give us some answers here? It is very annoying thing that we can't use Unity Interaction toolkit in 2020.x with Valve.

**Comment by zite** [comment] 2020-10-20 00:08
Closing as duplicate of #16

**Closed by zite** 2020-10-20 00:08 UTC
Labels: duplicate
