### ISSUE TITLE
OpenVR, SteamVR and HDRP

### ISSUE THREAD

**Issue by doktorbanana** [ValveSoftware/unity-xr-plugin#47] opened 2020-09-19 22:17 UTC
Hi,

i'm trying to use the SteamVR_Behaviour_Pose in a HDRP Project on a simple Cube GameObject. The following error appears:

NullReferenceException: Object reference not set to an instance of an object
Valve.VR.SteamVR_Action_Pose_Source.UpdateValue (System.Boolean skipStateAndEventUpdates) (at Assets/SteamVR/Input/SteamVR_Action_Pose.cs:575)
Valve.VR.SteamVR_Action_Skeleton_Source.UpdateValue (System.Boolean skipStateAndEventUpdates) (at Assets/SteamVR/Input/SteamVR_Action_Skeleton.cs:917)
Valve.VR.SteamVR_Action_Skeleton.UpdateValue (System.Boolean skipStateAndEventUpdates) (at Assets/SteamVR/Input/SteamVR_Action_Skeleton.cs:65)
Valve.VR.SteamVR_Input.UpdateSkeletonActions (System.Boolean skipSendingEvents) (at Assets/SteamVR/Input/SteamVR_Input.cs:355)
Valve.VR.SteamVR_Input.LateUpdate () (at Assets/SteamVR/Input/SteamVR_Input.cs:269)
Valve.VR.SteamVR_Behaviour.LateUpdate () (at Assets/SteamVR/Scripts/SteamVR_Behaviour.cs:238)
These are the settings i use:
image

I use the default Action Set. After generating it, the JSON looks like this:
I don't get whats going on. I just want to set the transform of the cube to the position of my controller.

Thanks for your help

**Comment by kisak-valve** [comment] 2020-09-19 22:28
Hello @doktorbanana, the same people see this issue tracker and the steamvr_unity_plugin issue tracker. Closing as a duplicate of https://github.com/ValveSoftware/steamvr_unity_plugin/issues/837.

**Closed by kisak-valve** 2020-09-19 22:28 UTC

**Comment by doktorbanana** [comment] 2020-09-19 23:02
oh ok. sorry
