### ISSUE TITLE
OpenVR XR Plugin 1.0.1 Crashes Editor on Initialization (in SetUserDefinedSettings)

### ISSUE THREAD

**Issue by gavaga** [ValveSoftware/unity-xr-plugin#52] opened 2020-09-28 15:16 UTC
We have been dealing with an OpenVR XR Plugin crash bug for a while now, where we get a hard crash in the Editor (uncaught native exception) when OpenVR is initialized. It was initially observed in the XR Management `RuntimeInitializeOnLoad` sequence with the OpenVR plugin enabled for desktop, so we moved to initializing OpenVR and SteamVR from `MonoBehaviour.Awake/Start` in the scene, which seemed to resolve it, but that's now crashing, as well. It's not 100% consistent, but around 4/5 times we hit Play it crashes.

Observed on OpenVR XR Plugin 1.0.1, with SteamVR Plugin 2.6.0b4, editor versions 2019.3.6 and 2019.4.x. Never observed in a built Player.

Maybe duplicate, but the relevant issues I could find [steamvr#716](https://github.com/ValveSoftware/steamvr_unity_plugin/issues/716), [steamvr#704](https://github.com/ValveSoftware/steamvr_unity_plugin/issues/704) don't seem to have quite the same failure mode, and claim to be resolved in the versions we're using.

Relevant part of the stack trace (above this in the chain is `MonoBehaviour.Start()` on our loader `GameObject`):
<img width="729" alt="stacktrace" src="https://user-images.githubusercontent.com/5473775/94444390-488d8380-0174-11eb-8213-e88a5fd1b6a7.PNG">

Relevant section of Editor log: https://pastebin.com/SmY9LKGF

**Comment by hnguyen094** [comment] 2020-10-06 18:27
We also noticed that the Editor crashes 100% of the time when we set OpenVR to Multi Pass, as some of the other relevant issue threads have discussed as a potential fix. 
Here is the stacktrace from Editor.log: [https://pastebin.com/ZsPfpZTh](https://pastebin.com/ZsPfpZTh)

**Comment by WBoode** [comment] 2020-10-12 13:47
We are encountering the same issue. 
Unity 2019.4.x (currently .10)
OpenXR VR version 1.0.1
SteamVR 1.14.16

**Comment by zite** [comment] 2020-10-20 21:52
I'm having trouble reproducing this, can one of you provide a simple example project? @WBoode @hnguyen094 @gavaga

**Comment by zite** [comment] 2020-12-03 23:04
Closed due to inactivity.

**Comment by CoderDawson** [comment] 2020-12-15 00:24
@zite I am actively running into this same issue right now with Unity 2019.4.16f1, Plugin 1.0.1, and SteamVR 1.15.12. 

In my particular case the Unity Editor just "goes away", the Unity crash handler doesn't catch the issue, and no crash dump is generated. Unfortunately, I do not have a repro project yet as the issue is random most of the time. 

I connected the Visual Studio debugger to Unity to see if I could get any extra information on what was occurring and with the debugger attached the Unity Editor doesn't die at all but it triggers two break points in the ntdll.dll with exceptions regarding heap corruption.

Looking at the [SetUserDefinedSettings ](https://github.com/ValveSoftware/unity-xr-plugin/blob/4c7620c6056b91d74f0a360128c18de1dcdac905/Providers/UserProjectSettings.cpp#L376) function in the UserProjectSettings.cpp code, I am hoping that the main part of the problem is the buffer overruns occurring when copying the [editorAppKey](https://github.com/ValveSoftware/unity-xr-plugin/blob/4c7620c6056b91d74f0a360128c18de1dcdac905/Providers/UserProjectSettings.cpp#L394), [actionManifestPath](https://github.com/ValveSoftware/unity-xr-plugin/blob/4c7620c6056b91d74f0a360128c18de1dcdac905/Providers/UserProjectSettings.cpp#L403), and/or [appName](https://github.com/ValveSoftware/unity-xr-plugin/blob/4c7620c6056b91d74f0a360128c18de1dcdac905/Providers/UserProjectSettings.cpp#L425) strings where the buffer is allocated using strlen but the strcpy is using strlen + 1.

**Comment by CoderDawson** [comment] 2020-12-15 01:06
@zite I made the buffer overrun fixes locally and I no longer seem to be able to duplicate the Unity dying issue after many multiple enter and exit playmode attempts. Let me know if commenting on this issue is enough or if you need me to make a new issue to get the fix in.

**Comment by zite** [comment] 2020-12-15 01:09
Can you verify that you're getting the right number of characters for those variables (like does the app name show up right in steamvr) I was under the impression the +1 accounted for the null terminator.

**Comment by CoderDawson** [comment] 2020-12-15 01:43
The +1 in the strcpy call is correct to include the null terminator. The problem is that the buffer was allocated using the value return by strlen, which does not include the null terminator in the count. This results in the strcpy call writing one byte passed the end of the buffer. The fix is to add a +1 to the strlen result when the buffers for the strings mentioned above are allocated. 

However, I will confirm the character count and SteamVR display in the morning if you feel it is still necessary.

**Comment by CoderDawson** [comment] 2020-12-15 16:01
@zite I have confirmed the character count and SteamVR display is correct when entering playmode with the fix to increase the allocated buffer size by one to match the strcpy call size.

**Comment by CoderDawson** [comment] 2020-12-16 20:02
@zite This pull request has my proposed changes: https://github.com/ValveSoftware/unity-xr-plugin/pull/72

**Comment by OwlchemyDawson** [comment] 2020-12-16 23:50
Make that pull request https://github.com/ValveSoftware/unity-xr-plugin/pull/73.

**Comment by OwlchemyDawson** [comment] 2020-12-18 16:21
@zite Is there anything further I can provide to get this issue resolved?

**Comment by zite** [comment] 2020-12-18 16:35
Ah thanks for the fix and ping. Will see to it now.

**Comment by zite** [comment] 2020-12-18 17:11
Thanks all, give the latest release a try: https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.2b

**Comment by OwlchemyDawson** [comment] 2021-01-04 19:55
@zite The change made to [UserProjectSettings.cpp](https://github.com/ValveSoftware/unity-xr-plugin/commit/a6e7bcc7a36b60dc75b44a3bca0948fb8635f8ae) is incorrect; the "+ 1" addition needs to come after the end strlen call parenthesis. Are you not able to take pull request #73 that I submitted?

**Comment by KospY** [comment] 2021-01-06 13:47
Recently updated to Unity XR plugin, as soon as we switch to openVR the editor always crash the second time we play the editor. 
We are using OpenVR XR plugins 1.1.3.
This issue is a pain and it seem the pull request doesn't have been pushed, please fix!

**Comment by Willoww97** [comment] 2021-01-07 11:47
We recently upgraded our project for the Unity XR plugin and openVR (1.1.3). It's consistently crashing each 2nd play in the inspector. In the changelogs latest update, it's stated to be fixed but the issue persists for us. Unable to continue development with this version.

**Comment by OwlchemyDawson** [comment] 2021-01-07 17:59
@zite @kisak-valve Is there anything I can do to help get the correct fix integrated?

**Comment by zite** [comment] 2021-01-11 20:58
Sorry everybody, looks like there was a merge bug. I believe this has been fixed now in 1.1.4. https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.4

**Comment by KospY** [comment] 2021-01-12 11:06
Seem to work now with 1.1.4, no more crashes :)
Thanks!

**Comment by kisak-valve** [comment] 2021-02-12 16:20
Closing as fixed.

**Closed by kisak-valve** 2021-02-12 16:20 UTC
Labels: Need Retest, fixed in next version
